
services:
  # PostgreSQL servisi
  postgres:
    image: postgres:latest
    container_name: moviedb-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - moviedb-network

  # Spring Boot uygulaması
  app:
    build: .  # Dockerfile'dan build et
    container_name: moviedb-app
    depends_on:
      - postgres  # Önce PostgreSQL başlasın
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    networks:
      - moviedb-network

# Verilerin kalıcı olması için volume tanımla
volumes:
  postgres_data:

# Container'ların birbiriyle haberleşmesi için network tanımla
networks:
  moviedb-network:
    driver: bridge
